// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import Link from 'next/link'
import "./globals.css";
export default function Layout({ children }: { children: React.ReactNode }) {
  return (

    <html lang="en">
      <head>
      </head>
      <body>
        <div className="min-h-screen bg-gray-100 text-gray-900">
          {/* ✅ Navbar */}
          <Navbar />

          {/* ✅ Page Content */}
          <main className="container mx-auto px-4 py-6">{children}</main>
        </div>


        {/* ✅ Footer */}
        <Footer />
      </body>
    </html>
  );
}


/* ✅ Navbar Component */
function Navbar() {
  return (
    <nav className="bg-blue-600 text-white py-4 shadow-md">
      <div className="container mx-auto px-6 flex justify-between items-center">
        {/* ✅ Brand */}

        <h1 className="text-2xl font-bold">
          <Link href="/">{process.env.NEXT_PUBLIC_BLOG_NAME}</Link>
        </h1>

        {/* ✅ Nav Links */}
        <div className="hidden md:flex space-x-6">
          <NavLink href="/">Home</NavLink>
          <NavLink href="/about">About</NavLink>
          <NavLink href="/contact">Contact</NavLink>

          {/* ✅ Dropdown for Categories */}
          <div className="relative group">
            <button className="hover:underline flex items-center">
              Categories ▼
            </button>
            <div className="absolute left-0 mt-2 w-40 bg-white text-gray-900 rounded-lg shadow-lg opacity-0 group-hover:opacity-100 transition-opacity duration-200">
              <DropdownItem href="/category/tech">Tech</DropdownItem>
              <DropdownItem href="/category/lifestyle">Lifestyle</DropdownItem>
              <DropdownItem href="/category/travel">Travel</DropdownItem>
            </div>
          </div>
        </div>

        {/* ✅ Mobile Menu Button */}
        <div className="md:hidden">
          <button className="text-white text-xl">☰</button>
        </div>
      </div>
    </nav>
  );
}

/* ✅ Reusable Nav Link */
function NavLink({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a href={href} className="hover:underline">
      {children}
    </a>
  );
}

/* ✅ Dropdown Item */
function DropdownItem({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a href={href} className="block px-4 py-2 hover:bg-gray-200">
      {children}
    </a>
  );
}


/* ✅ Footer Component */
function Footer() {
  return (
    <footer className="bg-gray-800 text-white py-6 mt-12">
      <div className="container mx-auto px-6 text-center">
        <p className="text-lg font-semibold">Follow Us</p>
        <div className="flex justify-center space-x-6 my-3">
          <SocialIcon href="https://facebook.com" icon="📘" label="Facebook" />
          <SocialIcon href="https://twitter.com" icon="🐦" label="Twitter" />
          <SocialIcon href="https://instagram.com" icon="📸" label="Instagram" />
        </div>
        <p className="text-sm text-gray-400">© 2025 My Blog. All rights reserved.</p>
      </div>
    </footer>
  );
}


/* ✅ Social Media Icon */
function SocialIcon({ href, icon, label }: { href: string; icon: string; label: string }) {
  return (
    <a href={href} target="_blank" rel="noopener noreferrer" className="text-2xl hover:text-blue-400">
      <span role="img" aria-label={label}>{icon}</span>
    </a>
  );
}